-- Ouroville Motors — execute este script no SQL Editor do seu projeto Supabase.

create extension if not exists pg_trgm;

-- ========== TABELAS ==========
create table if not exists public.carros (
  id bigint generated by default as identity primary key,
  marca text not null,
  modelo text not null,
  versao text,
  ano int not null,
  ano_modelo int,
  preco numeric,
  quilometragem int,
  combustivel text,
  cambio text,
  cor text,
  fotos text[] default '{}',
  descricao text,
  destaque text,
  status text not null default 'disponivel' check (status in ('disponivel','vendido')),
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text,
  email text,
  carro_interesse text,
  mensagem text,
  consentimento boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create index if not exists carros_busca_idx on public.carros
  using gin ((marca || ' ' || modelo || ' ' || coalesce(versao,'')) gin_trgm_ops);

-- ========== GRANTS ==========
grant select on public.carros to anon, authenticated;
grant insert, update, delete on public.carros to authenticated;
grant insert on public.leads to anon, authenticated;
grant select, delete on public.leads to authenticated;
grant select on public.admins to authenticated;
grant all on public.carros, public.leads, public.admins to service_role;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ========== RLS ==========
alter table public.carros enable row level security;
alter table public.leads  enable row level security;
alter table public.admins enable row level security;

create or replace function public.is_admin(_uid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = _uid)
$$;

drop policy if exists "carros disponiveis publicos" on public.carros;
create policy "carros disponiveis publicos" on public.carros
  for select to anon, authenticated using (status = 'disponivel' or public.is_admin(auth.uid()));

drop policy if exists "admin gerencia carros" on public.carros;
create policy "admin gerencia carros" on public.carros
  for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "qualquer um cria lead" on public.leads;
create policy "qualquer um cria lead" on public.leads
  for insert to anon, authenticated with check (true);

drop policy if exists "admin le leads" on public.leads;
create policy "admin le leads" on public.leads
  for select to authenticated using (public.is_admin(auth.uid()));

drop policy if exists "admin apaga leads" on public.leads;
create policy "admin apaga leads" on public.leads
  for delete to authenticated using (public.is_admin(auth.uid()));

drop policy if exists "ler proprio admin" on public.admins;
create policy "ler proprio admin" on public.admins
  for select to authenticated using (user_id = auth.uid());

-- ========== STORAGE (fotos dos carros) ==========
insert into storage.buckets (id, name, public) values ('carros','carros', true)
  on conflict (id) do nothing;

drop policy if exists "fotos publicas" on storage.objects;
create policy "fotos publicas" on storage.objects
  for select using (bucket_id = 'carros');

drop policy if exists "admin envia fotos" on storage.objects;
create policy "admin envia fotos" on storage.objects
  for all to authenticated
  using (bucket_id = 'carros' and public.is_admin(auth.uid()))
  with check (bucket_id = 'carros' and public.is_admin(auth.uid()));

-- ========== ADMIN ==========
-- Depois de criar seu usuário em Authentication > Users, rode:
-- insert into public.admins (user_id) select id from auth.users where email = 'SEU@EMAIL.com';
