-- Ouroville Motors — execute este script no SQL Editor do seu projeto Supabase.

create extension if not exists pg_trgm;

-- ========== TABELAS ==========
create table if not exists public.carros (
  id bigint generated by default as identity primary key,
  marca text not null,
  modelo text not null,
  versao text,
  ano int not null,
  ano_modelo int,
  preco numeric,
  quilometragem int,
  combustivel text,
  cambio text,
  cor text,
  motor text,
  tracao text,
  fotos text[] default '{}',
  descricao text,
  destaque text,
  status text not null default 'disponivel' check (status in ('disponivel','vendido')),
  created_at timestamptz not null default now()
);

-- Mantém bancos já criados compatíveis com o painel administrativo.
alter table public.carros add column if not exists motor text;
alter table public.carros add column if not exists tracao text;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('site_visit', 'car_view', 'whatsapp_click')),
  car_id bigint references public.carros(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists carros_busca_idx on public.carros
  using gin ((marca || ' ' || modelo || ' ' || coalesce(versao,'')) gin_trgm_ops);
create index if not exists analytics_events_car_idx on public.analytics_events (car_id, event_type);

-- ========== GRANTS ==========
grant select on public.carros to anon, authenticated;
grant insert, update, delete on public.carros to authenticated;
grant select on public.admins to authenticated;
grant select on public.analytics_events to authenticated;
grant all on public.carros, public.admins, public.analytics_events to service_role;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ========== RLS ==========
alter table public.carros enable row level security;
alter table public.admins enable row level security;
alter table public.analytics_events enable row level security;

create or replace function public.is_admin(_uid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = _uid)
$$;

drop policy if exists "carros disponiveis publicos" on public.carros;
create policy "carros disponiveis publicos" on public.carros
  for select to anon, authenticated using (status = 'disponivel' or public.is_admin(auth.uid()));

drop policy if exists "admin gerencia carros" on public.carros;
create policy "admin gerencia carros" on public.carros
  for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "ler proprio admin" on public.admins;
create policy "ler proprio admin" on public.admins
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "admin ve metricas" on public.analytics_events;
create policy "admin ve metricas" on public.analytics_events
  for select to authenticated using (public.is_admin(auth.uid()));

create or replace function public.track_analytics_event(
  _event_type text,
  _car_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if _event_type not in ('site_visit', 'car_view', 'whatsapp_click') then
    raise exception 'Evento inválido.';
  end if;

  if _event_type = 'site_visit' and _car_id is not null then
    raise exception 'Evento inválido.';
  end if;

  if _event_type in ('car_view', 'whatsapp_click') and not exists (select 1 from public.carros where id = _car_id) then
    raise exception 'Veículo inválido.';
  end if;

  insert into public.analytics_events (event_type, car_id) values (_event_type, _car_id);
end;
$$;

revoke all on function public.track_analytics_event(text, bigint) from public;
grant execute on function public.track_analytics_event(text, bigint) to anon, authenticated;

-- ========== STORAGE (fotos dos carros) ==========
insert into storage.buckets (id, name, public) values ('carros','carros', true)
  on conflict (id) do nothing;

drop policy if exists "fotos publicas" on storage.objects;
create policy "fotos publicas" on storage.objects
  for select using (bucket_id = 'carros');

drop policy if exists "admin envia fotos" on storage.objects;
create policy "admin envia fotos" on storage.objects
  for all to authenticated
  using (bucket_id = 'carros' and public.is_admin(auth.uid()))
  with check (bucket_id = 'carros' and public.is_admin(auth.uid()));

-- ========== ADMIN ==========
-- Depois de criar seu usuário em Authentication > Users, rode:
-- insert into public.admins (user_id) select id from auth.users where email = 'SEU@EMAIL.com';
