-- Ouroville Motors — execute este script no SQL Editor do seu projeto Supabase.

create extension if not exists pg_trgm;

-- ========== TABELAS ==========
create table if not exists public.carros (
  id bigint generated by default as identity primary key,
  marca text not null,
  modelo text not null,
  versao text,
  ano int not null,
  ano_modelo int,
  preco numeric,
  quilometragem int,
  combustivel text,
  cambio text,
  cor text,
  motor text,
  tracao text,
  fotos text[] default '{}',
  descricao text,
  destaque text,
  status text not null default 'disponivel' check (status in ('disponivel','vendido')),
  created_at timestamptz not null default now()
);

-- Mantém bancos já criados compatíveis com o painel administrativo.
alter table public.carros add column if not exists motor text;
alter table public.carros add column if not exists tracao text;

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text,
  email text,
  carro_interesse text,
  mensagem text,
  consentimento boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create index if not exists carros_busca_idx on public.carros
  using gin ((marca || ' ' || modelo || ' ' || coalesce(versao,'')) gin_trgm_ops);

-- ========== GRANTS ==========
grant select on public.carros to anon, authenticated;
grant insert, update, delete on public.carros to authenticated;
grant select, delete on public.leads to authenticated;
grant select on public.admins to authenticated;
grant all on public.carros, public.leads, public.admins to service_role;
grant usage, select on all sequences in schema public to anon, authenticated;

-- ========== RLS ==========
alter table public.carros enable row level security;
alter table public.leads  enable row level security;
alter table public.admins enable row level security;

create or replace function public.is_admin(_uid uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = _uid)
$$;

drop policy if exists "carros disponiveis publicos" on public.carros;
create policy "carros disponiveis publicos" on public.carros
  for select to anon, authenticated using (status = 'disponivel' or public.is_admin(auth.uid()));

drop policy if exists "admin gerencia carros" on public.carros;
create policy "admin gerencia carros" on public.carros
  for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));

drop policy if exists "qualquer um cria lead" on public.leads;

drop policy if exists "admin le leads" on public.leads;
create policy "admin le leads" on public.leads
  for select to authenticated using (public.is_admin(auth.uid()));

drop policy if exists "admin apaga leads" on public.leads;
create policy "admin apaga leads" on public.leads
  for delete to authenticated using (public.is_admin(auth.uid()));

drop policy if exists "ler proprio admin" on public.admins;
create policy "ler proprio admin" on public.admins
  for select to authenticated using (user_id = auth.uid());

-- Recebe contatos públicos com validação e uma limitação simples de repetição.
-- A inserção direta fica bloqueada; o site chama esta função RPC.
create or replace function public.submit_lead(
  _nome text,
  _telefone text,
  _mensagem text,
  _consentimento boolean
)
returns public.leads
language plpgsql
security definer
set search_path = public
as $$
declare
  novo_lead public.leads;
begin
  if not _consentimento then
    raise exception 'Consentimento é obrigatório.';
  end if;

  if char_length(trim(coalesce(_nome, ''))) < 2 or char_length(trim(coalesce(_nome, ''))) > 120 then
    raise exception 'Nome inválido.';
  end if;

  if char_length(trim(coalesce(_telefone, ''))) < 8 or char_length(trim(coalesce(_telefone, ''))) > 30 then
    raise exception 'Telefone inválido.';
  end if;

  if char_length(trim(coalesce(_mensagem, ''))) > 2000 then
    raise exception 'Mensagem muito longa.';
  end if;

  if exists (
    select 1 from public.leads
    where telefone = trim(_telefone)
      and created_at > now() - interval '5 minutes'
  ) then
    raise exception 'Aguarde alguns minutos antes de enviar outra mensagem.';
  end if;

  insert into public.leads (nome, telefone, mensagem, consentimento)
  values (trim(_nome), trim(_telefone), nullif(trim(coalesce(_mensagem, '')), ''), true)
  returning * into novo_lead;

  return novo_lead;
end;
$$;

revoke all on function public.submit_lead(text, text, text, boolean) from public;
grant execute on function public.submit_lead(text, text, text, boolean) to anon, authenticated;

-- ========== STORAGE (fotos dos carros) ==========
insert into storage.buckets (id, name, public) values ('carros','carros', true)
  on conflict (id) do nothing;

drop policy if exists "fotos publicas" on storage.objects;
create policy "fotos publicas" on storage.objects
  for select using (bucket_id = 'carros');

drop policy if exists "admin envia fotos" on storage.objects;
create policy "admin envia fotos" on storage.objects
  for all to authenticated
  using (bucket_id = 'carros' and public.is_admin(auth.uid()))
  with check (bucket_id = 'carros' and public.is_admin(auth.uid()));

-- ========== ADMIN ==========
-- Depois de criar seu usuário em Authentication > Users, rode:
-- insert into public.admins (user_id) select id from auth.users where email = 'SEU@EMAIL.com';
