-- Run this once in Supabase SQL Editor for an existing Ouroville database.

alter table public.carros add column if not exists motor text;
alter table public.carros add column if not exists tracao text;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('site_visit', 'car_view', 'whatsapp_click')),
  car_id bigint references public.carros(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_car_idx on public.analytics_events (car_id, event_type);
grant select on public.analytics_events to authenticated;
alter table public.analytics_events enable row level security;

drop policy if exists "admin ve metricas" on public.analytics_events;
create policy "admin ve metricas" on public.analytics_events
  for select to authenticated using (public.is_admin(auth.uid()));

create or replace function public.track_analytics_event(_event_type text, _car_id bigint default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if _event_type not in ('site_visit', 'car_view', 'whatsapp_click') then raise exception 'Evento inválido.'; end if;
  if _event_type = 'site_visit' and _car_id is not null then raise exception 'Evento inválido.'; end if;
  if _event_type in ('car_view', 'whatsapp_click') and not exists (select 1 from public.carros where id = _car_id) then raise exception 'Veículo inválido.'; end if;
  insert into public.analytics_events (event_type, car_id) values (_event_type, _car_id);
end;
$$;

revoke all on function public.track_analytics_event(text, bigint) from public;
grant execute on function public.track_analytics_event(text, bigint) to anon, authenticated;
